meta_product_name: "Charlie Jeppsson"
meta_title: "Charlie Jeppsson - Full stack web developer"
meta_description: "Developer fluent in Ruby on Rails, JavaScript, Node.js, MongoDB, React.js, Angular2, HTML/CSS, ActiveRecord, PostgreSQL, Bootstrap, Git, GitHub, Heroku and more! Currently looking for full stack and back-end opportunities."
meta_image: "meta-portfolio-image.png"
